train:
    dataset_class: FlatEmbeddingDataset
    base_dir: data/MNISTEmbeddings/mnist_train_embeddings.npy
    train: true

test:
    dataset_class: FlatEmbeddingDataset
    base_dir: data/MNISTEmbeddings/mnist_test_embeddings.npy
    train: false