train:
    dataset_class: FlatEmbeddingDataset
    base_dir: data/OCTMNISTEmbeddings/octmnist_train_embeddings.npy
    train: true

test:
    dataset_class: FlatEmbeddingDataset
    base_dir: data/OCTMNISTEmbeddings/octmnist_test_embeddings.npy
    train: false