program: train_model.py
name: VAE_arch_optimization_v4
method: grid
metric:
    goal: minimize
    name: test_loss
parameters:
    in_features:
        value: 784
    hidden_size:
        values: [256, 128, 64, 32, 16, 8]
    layers:
        values: [16, 8, 4, 2]