train:
    dataset_class: GraphEmbeddedDataset
    base_dir: data/MNISTGraph/mnist_train_knn_graph-100.pkl
    train: true
    smsl_setting: true

test:
    dataset_class: GraphEmbeddedDataset
    base_dir: data/MNISTGraph/mnist_test_knn_graph-100.pkl
    train: false
    smsl_setting: true